# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{facebooker-rails3}
  s.version = "1.0.65"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["chad@chadfowler.com", "tarsolya@gmail.com"]
  s.date = %q{2010-08-09}
  s.description = %q{Facebooker for Rails 3}
  s.email = %q{tarsolya@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "generators/facebook/facebook_generator.rb",
     "generators/facebook/templates/config/facebooker.yml",
     "generators/facebook/templates/public/javascripts/facebooker.js",
     "generators/facebook_controller/USAGE",
     "generators/facebook_controller/facebook_controller_generator.rb",
     "generators/facebook_controller/templates/controller.rb",
     "generators/facebook_controller/templates/functional_test.rb",
     "generators/facebook_controller/templates/helper.rb",
     "generators/facebook_controller/templates/view.fbml.erb",
     "generators/facebook_controller/templates/view.html.erb",
     "generators/facebook_publisher/facebook_publisher_generator.rb",
     "generators/facebook_publisher/templates/create_facebook_templates.rb",
     "generators/facebook_publisher/templates/publisher.rb",
     "generators/facebook_scaffold/USAGE",
     "generators/facebook_scaffold/facebook_scaffold_generator.rb",
     "generators/facebook_scaffold/templates/controller.rb",
     "generators/facebook_scaffold/templates/facebook_style.css",
     "generators/facebook_scaffold/templates/functional_test.rb",
     "generators/facebook_scaffold/templates/helper.rb",
     "generators/facebook_scaffold/templates/layout.fbml.erb",
     "generators/facebook_scaffold/templates/layout.html.erb",
     "generators/facebook_scaffold/templates/style.css",
     "generators/facebook_scaffold/templates/view_edit.fbml.erb",
     "generators/facebook_scaffold/templates/view_edit.html.erb",
     "generators/facebook_scaffold/templates/view_index.fbml.erb",
     "generators/facebook_scaffold/templates/view_index.html.erb",
     "generators/facebook_scaffold/templates/view_new.fbml.erb",
     "generators/facebook_scaffold/templates/view_new.html.erb",
     "generators/facebook_scaffold/templates/view_show.fbml.erb",
     "generators/facebook_scaffold/templates/view_show.html.erb",
     "generators/publisher/publisher_generator.rb",
     "generators/xd_receiver/templates/xd_receiver.html",
     "generators/xd_receiver/templates/xd_receiver_ssl.html",
     "generators/xd_receiver/xd_receiver_generator.rb",
     "lib/facebooker.rb",
     "lib/facebooker/adapters/adapter_base.rb",
     "lib/facebooker/adapters/bebo_adapter.rb",
     "lib/facebooker/adapters/facebook_adapter.rb",
     "lib/facebooker/admin.rb",
     "lib/facebooker/application.rb",
     "lib/facebooker/attachment.rb",
     "lib/facebooker/batch_request.rb",
     "lib/facebooker/data.rb",
     "lib/facebooker/feed.rb",
     "lib/facebooker/logging.rb",
     "lib/facebooker/mobile.rb",
     "lib/facebooker/mock/service.rb",
     "lib/facebooker/mock/session.rb",
     "lib/facebooker/model.rb",
     "lib/facebooker/models/affiliation.rb",
     "lib/facebooker/models/album.rb",
     "lib/facebooker/models/applicationproperties.rb",
     "lib/facebooker/models/applicationrestrictions.rb",
     "lib/facebooker/models/comment.rb",
     "lib/facebooker/models/cookie.rb",
     "lib/facebooker/models/education_info.rb",
     "lib/facebooker/models/event.rb",
     "lib/facebooker/models/family_relative_info.rb",
     "lib/facebooker/models/friend_list.rb",
     "lib/facebooker/models/group.rb",
     "lib/facebooker/models/info_item.rb",
     "lib/facebooker/models/info_section.rb",
     "lib/facebooker/models/location.rb",
     "lib/facebooker/models/message_thread.rb",
     "lib/facebooker/models/notifications.rb",
     "lib/facebooker/models/page.rb",
     "lib/facebooker/models/photo.rb",
     "lib/facebooker/models/tag.rb",
     "lib/facebooker/models/user.rb",
     "lib/facebooker/models/video.rb",
     "lib/facebooker/models/work_info.rb",
     "lib/facebooker/parser.rb",
     "lib/facebooker/rails/backwards_compatible_param_checks.rb",
     "lib/facebooker/rails/controller.rb",
     "lib/facebooker/rails/cucumber.rb",
     "lib/facebooker/rails/cucumber/world.rb",
     "lib/facebooker/rails/extensions/action_controller.rb",
     "lib/facebooker/rails/extensions/action_view.rb",
     "lib/facebooker/rails/extensions/rack_setup.rb",
     "lib/facebooker/rails/extensions/routing.rb",
     "lib/facebooker/rails/facebook_form_builder.rb",
     "lib/facebooker/rails/facebook_pretty_errors.rb",
     "lib/facebooker/rails/facebook_request_fix.rb",
     "lib/facebooker/rails/facebook_request_fix_2-3.rb",
     "lib/facebooker/rails/facebook_session_handling.rb",
     "lib/facebooker/rails/facebook_url_helper.rb",
     "lib/facebooker/rails/facebook_url_rewriting.rb",
     "lib/facebooker/rails/helpers.rb",
     "lib/facebooker/rails/helpers/fb_connect.rb",
     "lib/facebooker/rails/helpers/stream_publish.rb",
     "lib/facebooker/rails/integration_session.rb",
     "lib/facebooker/rails/profile_publisher_extensions.rb",
     "lib/facebooker/rails/publisher.rb",
     "lib/facebooker/rails/routing.rb",
     "lib/facebooker/rails/test_helpers.rb",
     "lib/facebooker/rails/utilities.rb",
     "lib/facebooker/railtie.rb",
     "lib/facebooker/server_cache.rb",
     "lib/facebooker/service.rb",
     "lib/facebooker/service/base_service.rb",
     "lib/facebooker/service/curl_service.rb",
     "lib/facebooker/service/net_http_service.rb",
     "lib/facebooker/service/typhoeus_multi_service.rb",
     "lib/facebooker/service/typhoeus_service.rb",
     "lib/facebooker/session.rb",
     "lib/facebooker/stream_post.rb",
     "lib/facebooker/version.rb",
     "lib/net/http_multipart_post.rb",
     "lib/rack/facebook.rb",
     "lib/rack/facebook_session.rb",
     "lib/tasks/facebooker.rake",
     "lib/tasks/facebooker.rb",
     "lib/tasks/tunnel.rake",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/tarsolya/facebooker-rails3}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Facebooker for Rails 3}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

